Repository teamulster/soHappy, pull requests merged in 2020-09, with the labels that each got.

#19 NO TICKET adapt detekt config
  app/src/androidTest/java/de/hsaugsburg/teamulster/sohappy/BitmapEditorTest.kt
  app/src/androidTest/java/de/hsaugsburg/teamulster/sohappy/HaarCascadeFaceDetectorTest.kt
  app/src/androidTest/java/de/hsaugsburg/teamulster/sohappy/detector/FerTFLiteSmileDetectorImplTest.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/CameraActivity.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/analyzer/BitmapEditor.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/analyzer/ImageAnalyzer.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/analyzer/detector/FaceDetector.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/analyzer/detector/SmileDetector.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/analyzer/detector/facedetectorimpl/HaarCascadeFaceDetector.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/analyzer/detector/smiledetectorimpl/AbstractTFLiteSmileDetector.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/analyzer/detector/smiledetectorimpl/FerTFLiteSmileDetectorImpl.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/config/ConfigManager.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/config/ImageAnalyzerConfig.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/config/MainConfig.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/exceptions/InvalidJsonStringException.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/notification/NotificationBroadcastReceiver.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/notification/NotificationHandler.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/util/YuvToRgbConverter.kt
  build.gradle
  detekt.yml
Labels: implement

#18 25 Refactor tests
  app/src/androidTest/java/de/hsaugsburg/teamulster/sohappy/HaarCascadeFaceDetectorTest.kt
  app/src/androidTest/java/de/hsaugsburg/teamulster/sohappy/detector/FerTFLiteSmileDetectorImplTest.kt
Labels: refactoring

#13 16 implement queue
  .editorconfig
  app/build.gradle
  app/src/androidTest/java/de/hsaugsburg/teamulster/sohappy/detector/FerTFLiteSmileDetectorImplTest.kt
  app/src/androidTest/java/de/hsaugsburg/teamulster/sohappy/queue/BitmapQueueTest.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/CameraActivity.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/analyzer/ImageAnalyzer.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/analyzer/detector/facedetectorimpl/HaarCascadeFaceDetector.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/factories/DetectorFactory.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/queue/BitmapQueue.kt
Labels: implement

#21 35 Implement DetectionResult collector
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/CameraActivity.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/analyzer/ImageAnalyzer.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/analyzer/collector/Measurement.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/analyzer/detector/DetectionResult.kt
Labels: implement

#22 #4 - UI Design
  app/build.gradle
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/CameraActivity.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/analyzer/ImageAnalyzer.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/fragment/CameraFragment.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/fragment/HelpFragment.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/fragment/HomeFragment.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/fragment/JokesFragment.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/fragment/Questionnaire01Fragment.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/fragment/Questionnaire02Fragment.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/fragment/Questionnaire03Fragment.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/fragment/Questionnaire04Fragment.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/fragment/Questionnaire05Fragment.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/fragment/Questionnaire06Fragment.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/fragment/ResultsFragment.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/fragment/SettingsFragment.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/fragment/SmileFragment.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/viewmodel/QuestionnaireViewModel.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/viewmodel/SettingsViewModel.kt
  app/src/main/res/animator/animation_checkmark.xml
  app/src/main/res/animator/animation_checkmark_circle.xml
  app/src/main/res/animator/animation_countdown.xml
  app/src/main/res/drawable/animated_checkmark.xml
  app/src/main/res/drawable/animated_countdown.xml
  app/src/main/res/drawable/button_background.xml
  app/src/main/res/drawable/button_background_blank.xml
  app/src/main/res/drawable/ic_baseline_arrow_drop_down_24.xml
  app/src/main/res/drawable/ic_baseline_keyboard_arrow_right_24.xml
  app/src/main/res/drawable/ic_checkmark.xml
  app/src/main/res/drawable/ic_countdown.xml
  app/src/main/res/drawable/ic_outline_emoji_emotions_24.xml
  app/src/main/res/drawable/overlay_background.xml
  app/src/main/res/drawable/rounded_background.xml
  app/src/main/res/drawable/search_background.xml
  app/src/main/res/drawable/spinner_background.xml
  app/src/main/res/layout/activity_camera.xml
  app/src/main/res/layout/fragment_camera.xml
  app/src/main/res/layout/fragment_help.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_jokes.xml
  app/src/main/res/layout/fragment_questionnaire_01.xml
  app/src/main/res/layout/fragment_questionnaire_02.xml
  app/src/main/res/layout/fragment_questionnaire_03.xml
  app/src/main/res/layout/fragment_questionnaire_04.xml
  app/src/main/res/layout/fragment_questionnaire_05.xml
  app/src/main/res/layout/fragment_questionnaire_06.xml
  app/src/main/res/layout/fragment_results.xml
  app/src/main/res/layout/fragment_settings.xml
  app/src/main/res/layout/fragment_smile.xml
  app/src/main/res/menu/overflow_menu.xml
  app/src/main/res/navigation/navigation.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: implement

#23 UI Design Privacy, Imprint, Credits
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/CameraActivity.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/fragment/HelpFragment.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/fragment/Questionnaire03Fragment.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/fragment/Questionnaire05Fragment.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/fragment/Questionnaire06Fragment.kt
Labels: implement

#31 #38 - NoSmile UI screen
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/fragment/NoSmileFragment.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/fragment/SmileFragment.kt
  app/src/main/res/drawable/button_background_contour.xml
  app/src/main/res/drawable/ic_nosmile.xml
  app/src/main/res/layout/fragment_nosmile.xml
  app/src/main/res/navigation/navigation.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: implement

#32 #50 - Restart Activity upon finish
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/fragment/ResultsFragment.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/fragment/SmileFragment.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/view/SpinnerCustom.kt
  app/src/main/res/layout/fragment_questionnaire_02.xml
  app/src/main/res/layout/fragment_questionnaire_04.xml
  app/src/main/res/navigation/navigation.xml
  app/src/main/res/values/strings.xml
Labels: implement

#33 42 Load state machine timer duration from config
  app/src/androidTest/java/de/hsaugsburg/teamulster/sohappy/config/ConfigManagerTest.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/CameraActivity.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/config/ConfigManager.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/config/MainConfig.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/config/SettingsConfig.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/config/TimerConfig.kt
Labels: implement, refactor

#30 36 implement SmileDetector/FaceDetector using Google ML Kit API
  app/build.gradle
  app/src/androidTest/assets/faceDetector_test_negative.jpg
  app/src/androidTest/assets/faceDetector_test_positive.jpg
  app/src/androidTest/assets/smileDetector_test_negative.png
  app/src/androidTest/assets/smileDetector_test_positive.jpg
  app/src/androidTest/java/de/hsaugsburg/teamulster/sohappy/analyzer/BitmapEditorTest.kt
  app/src/androidTest/java/de/hsaugsburg/teamulster/sohappy/analyzer/detector/FerTFLiteSmileDetectorImplTest.kt
  app/src/androidTest/java/de/hsaugsburg/teamulster/sohappy/analyzer/detector/GoogleMLKitAPIFaceDetectorTest.kt
  app/src/androidTest/java/de/hsaugsburg/teamulster/sohappy/analyzer/detector/GoogleMLKitAPISmileDetectorTest.kt
  app/src/androidTest/java/de/hsaugsburg/teamulster/sohappy/analyzer/detector/HaarCascadeFaceDetectorTest.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/analyzer/BitmapEditor.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/analyzer/detector/SmileDetector.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/analyzer/detector/facedetectorimpl/GoogleMLKitAPIFaceDetector.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/analyzer/detector/smiledetectorimpl/AbstractTFLiteSmileDetector.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/analyzer/detector/smiledetectorimpl/FerTFLiteSmileDetectorImpl.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/analyzer/detector/smiledetectorimpl/GoogleMLKitAPISmileDetector.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/factories/DetectorFactory.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/fragment/CameraFragment.kt
Labels: implement, refactor

#29 Added Logo
  .github/banner.png
  README.md
  app/src/main/assets/logo.png
  app/src/main/ic_launcher-playstore.png
  app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  app/src/main/res/drawable/ic_launcher_foreground.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.png
  app/src/main/res/mipmap-hdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  app/src/main/res/mipmap-mdpi/ic_launcher.png
  app/src/main/res/mipmap-mdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xhdpi/ic_launcher.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  app/src/main/res/values/ic_launcher_background.xml
Labels: implement

#34 11 Local Database
  app/build.gradle
  app/src/androidTest/java/de/hsaugsburg/teamulster/sohappy/analyzer/detector/FerTFLiteSmileDetectorTest.kt
  app/src/androidTest/java/de/hsaugsburg/teamulster/sohappy/analyzer/detector/HaarCascadeFaceDetectorTest.kt
  app/src/androidTest/java/de/hsaugsburg/teamulster/sohappy/config/ConfigManagerTest.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/CameraActivity.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/analyzer/ImageAnalyzer.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/analyzer/collector/Measurement.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/analyzer/detector/SmileDetector.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/analyzer/detector/smiledetectorimpl/AbstractTFLiteSmileDetector.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/analyzer/detector/smiledetectorimpl/FerTFLiteSmileDetector.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/analyzer/detector/smiledetectorimpl/GoogleMLKitAPISmileDetector.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/database/LocalDatabaseManager.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/fragment/CameraFragment.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/fragment/HistoryFragment.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/fragment/HomeFragment.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/fragment/NoSmileFragment.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/fragment/Questionnaire02Fragment.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/fragment/Questionnaire03Fragment.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/fragment/Questionnaire04Fragment.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/fragment/Questionnaire05Fragment.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/fragment/Questionnaire06Fragment.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/fragment/ResultsFragment.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/fragment/SmileFragment.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/stateMachine/Action.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/stateMachine/StateMachine.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/stateMachine/states/NoSmile.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/stateMachine/states/Questions.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/stateMachine/states/SmileCountdown.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/stateMachine/states/Start.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/stateMachine/states/State.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/stateMachine/states/Stimulus.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/stateMachine/states/TakeABreath.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/stateMachine/states/WaitingForFace.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/stateMachine/states/WaitingForSmile.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/util/StateMachineUtil.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/viewmodel/SettingsViewModel.kt
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/page_explanation_01.xml
  app/src/main/res/layout/page_explanation_02.xml
  app/src/main/res/layout/page_explanation_03.xml
  app/src/main/res/navigation/navigation.xml
Labels: implement, refactor

#37 10 video masker
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/VideoMasker.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/fragment/CameraFragment.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/fragment/SmileFragment.kt
  app/src/main/res/layout/fragment_smile.xml
  app/src/main/res/values/colors.xml
Labels: implement

#38 43 camera mirror inverted
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/analyzer/BitmapEditor.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/fragment/CameraFragment.kt
Labels: implement, refactor

#35 Build Pipeline
  .github/workflows/android-build.yml
Labels: implement

#41 renamed CameraActivity to MainActivity
  app/src/androidTest/java/de/hsaugsburg/teamulster/sohappy/analyzer/detector/FerTFLiteSmileDetectorTest.kt
  app/src/androidTest/java/de/hsaugsburg/teamulster/sohappy/analyzer/detector/GoogleMLKitAPIFaceDetectorTest.kt
  app/src/androidTest/java/de/hsaugsburg/teamulster/sohappy/analyzer/detector/GoogleMLKitAPISmileDetectorTest.kt
  app/src/androidTest/java/de/hsaugsburg/teamulster/sohappy/analyzer/detector/HaarCascadeFaceDetectorTest.kt
  app/src/androidTest/java/de/hsaugsburg/teamulster/sohappy/config/ConfigManagerTest.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/MainActivity.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/analyzer/ImageAnalyzer.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/fragment/ResultsFragment.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/notification/NotificationHandler.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/util/StateMachineUtil.kt
Labels: refactor

#40 47 Make DetectFactory load Impls with/without context
  app/src/androidTest/java/de/hsaugsburg/teamulster/sohappy/analyzer/BitmapEditorTest.kt
  app/src/androidTest/java/de/hsaugsburg/teamulster/sohappy/analyzer/detector/GoogleMLKitAPIFaceDetectorTest.kt
  app/src/androidTest/java/de/hsaugsburg/teamulster/sohappy/analyzer/detector/GoogleMLKitAPISmileDetectorTest.kt
  app/src/androidTest/java/de/hsaugsburg/teamulster/sohappy/factories/DetectorFactoryTest.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/analyzer/ImageAnalyzer.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/analyzer/detector/facedetectorimpl/GoogleMLKitAPIFaceDetector.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/analyzer/detector/smiledetectorimpl/GoogleMLKitAPISmileDetector.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/config/ConfigManager.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/factories/DetectorFactory.kt
Labels: implement, refactor

#39 Measurement is now a ViewModel
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/MainActivity.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/analyzer/ImageAnalyzer.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/database/LocalDatabaseManager.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/fragment/Questionnaire01Fragment.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/fragment/Questionnaire02Fragment.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/fragment/Questionnaire03Fragment.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/fragment/Questionnaire04Fragment.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/fragment/Questionnaire05Fragment.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/fragment/Questionnaire06Fragment.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/fragment/ResultsFragment.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/viewmodel/MeasurementViewModel.kt
Labels: implement, refactor

#36 Transformed StateMachine into ViewModel
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/MainActivity.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/analyzer/ImageAnalyzer.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/fragment/HomeFragment.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/fragment/NoSmileFragment.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/fragment/ResultsFragment.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/fragment/SmileFragment.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/stateMachine/StateMachine.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/util/StateMachineUtil.kt
Labels: refactor

#44 56 state fixes
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/MainActivity.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/VideoMasker.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/analyzer/ImageAnalyzer.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/analyzer/detector/facedetectorimpl/HaarCascadeFaceDetector.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/database/LocalDatabaseManager.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/fragment/CameraFragment.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/fragment/ExplanationFragment.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/fragment/NoSmileFragment.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/fragment/Questionnaire01Fragment.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/fragment/ResultsFragment.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/fragment/SmileFragment.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/stateMachine/Action.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/stateMachine/states/NoSmile.kt
  app/src/main/res/layout/fragment_smile.xml
Labels: implement, refactor

#42 #51 - Periodic Notifications
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/MainActivity.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/fragment/ResultsFragment.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/fragment/SettingsFragment.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/notification/NotificationBroadcastReceiver.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/notification/NotificationHandler.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/viewmodel/SettingsViewModel.kt
  app/src/main/res/layout/fragment_settings.xml
  app/src/main/res/values/strings.xml
Labels: implement

#43 Show history and result
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/fragment/HistoryFragment.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/fragment/ResultsFragment.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/viewmodel/MeasurementViewModel.kt
  app/src/main/res/layout/fragment_history.xml
  app/src/main/res/layout/fragment_results.xml
  app/src/main/res/layout/item_history_table.xml
  app/src/main/res/values/strings.xml
Labels: implement

#45 55 Exception Handling in UI
  .github/workflows/android-master.yml
  app/build.gradle
  app/src/androidTest/java/de/hsaugsburg/teamulster/sohappy/analyzer/detector/GoogleMLKitAPIFaceDetectorTest.kt
  app/src/androidTest/java/de/hsaugsburg/teamulster/sohappy/analyzer/detector/GoogleMLKitAPISmileDetectorTest.kt
  app/src/androidTest/java/de/hsaugsburg/teamulster/sohappy/analyzer/detector/SoHappyTFLiteSmileDetectorTest.kt
  app/src/androidTest/java/de/hsaugsburg/teamulster/sohappy/config/ConfigManagerTest.kt
  app/src/androidTest/java/de/hsaugsburg/teamulster/sohappy/factories/DetectorFactoryTest.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/MainActivity.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/analyzer/BitmapEditor.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/analyzer/ImageAnalyzer.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/analyzer/detector/DetectionResult.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/analyzer/detector/SmileDetector.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/analyzer/detector/facedetectorimpl/GoogleMLKitAPIFaceDetector.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/analyzer/detector/facedetectorimpl/HaarCascadeFaceDetector.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/analyzer/detector/smiledetectorimpl/AbstractTFLiteSmileDetector.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/analyzer/detector/smiledetectorimpl/FerTFLiteSmileDetector.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/config/ConfigManager.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/config/MainConfig.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/config/NotificationConfig.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/config/TimerConfig.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/exceptions/ExceptionHandler.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/exceptions/InvalidJsonStringException.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/factories/DetectorFactory.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/fragment/CameraFragment.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/fragment/ExplanationFragment.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/fragment/ExplanationPagerAdapter.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/fragment/HomeFragment.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/fragment/Questionnaire01Fragment.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/fragment/Questionnaire02Fragment.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/fragment/Questionnaire03Fragment.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/fragment/Questionnaire04Fragment.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/fragment/Questionnaire05Fragment.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/fragment/Questionnaire06Fragment.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/fragment/SmileFragment.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/notification/NotificationHandler.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/queue/BitmapQueue.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/stateMachine/states/SmileCountdown.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/viewmodel/QuestionnaireViewModel.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/viewmodel/SettingsViewModel.kt
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  build.gradle
Labels: implement, refactor

#48 46 bug fixes
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/VideoMasker.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/fragment/CameraFragment.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/fragment/NoSmileFragment.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/fragment/ResultsFragment.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/fragment/SmileFragment.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/stateMachine/Action.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/stateMachine/states/NoSmile.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/stateMachine/states/Questions.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/stateMachine/states/WaitingForFace.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/viewmodel/MeasurementViewModel.kt
Labels: implement, refactor

#47 #49 - Added Smile Detected Icon and Progress Bar
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/fragment/HomeFragment.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/fragment/SmileFragment.kt
  app/src/main/res/anim/pulse.xml
  app/src/main/res/anim/scale_up_fade.xml
  app/src/main/res/anim/scale_up_fade_small.xml
  app/src/main/res/anim/scale_up_logo.xml
  app/src/main/res/drawable/ic_pulse.xml
  app/src/main/res/drawable/ic_smile_detected.xml
  app/src/main/res/drawable/progress_background.xml
  app/src/main/res/layout/fragment_smile.xml
Labels: implement

#50 Master Fix
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/fragment/SmileFragment.kt
Labels: bug, refactor

#51 Moving progressbar up
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/fragment/SmileFragment.kt
  app/src/main/res/layout/fragment_smile.xml
Labels: bug, implement, refactor

#53 46 bug fixes
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/config/AboutConfig.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/config/ConfigManager.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/fragment/HelpFragment.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/fragment/SmileFragment.kt
Labels: implement

#54 fixed wrong textes
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/MainActivity.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/fragment/SmileFragment.kt
Labels: bug, implement

#55 NOTICKET Add Builder in Config classes
  app/src/androidTest/java/de/hsaugsburg/teamulster/sohappy/analyzer/detector/HaarCascadeFaceDetectorTest.kt
  app/src/androidTest/java/de/hsaugsburg/teamulster/sohappy/config/ConfigManagerTest.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/analyzer/detector/smiledetectorimpl/AbstractTFLiteSmileDetector.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/analyzer/detector/smiledetectorimpl/FerTFLiteSmileDetector.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/config/AboutConfig.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/config/ConfigManager.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/config/ImageAnalyzerConfig.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/config/MainConfig.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/config/NotificationConfig.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/config/SettingsConfig.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/config/TimerConfig.kt
Labels: implement, refactor

#56 Added FileHandler for QR-Codes and Files
  app/src/main/AndroidManifest.xml
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/LoadConfigActivity.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/config/ConfigManager.kt
  app/src/main/res/layout/activity_load_config.xml
  app/src/main/res/values/strings.xml
Labels: implement

#57 fixed the minimize issue
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/MainActivity.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/fragment/SmileFragment.kt
Labels: implement

#58 fixed bug, database now synchronized
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/LoadConfigActivity.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/database/LocalDatabaseManager.kt
Labels: implement

#61 64 Update README.md
  README.md
Labels: documentation

#63 notification now probably fixed
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/notification/NotificationHandler.kt
Labels: implement

#64 NOTICKET Remote config
  app/src/androidTest/java/de/hsaugsburg/teamulster/sohappy/config/ConfigManagerTest.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/config/ConfigManager.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/config/MainConfig.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/config/RemoteConfig.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/sync/RemoteSite.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/sync/RemoteSync.kt
Labels: implement

#65 cleanup code
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/LoadConfigActivity.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/analyzer/ImageAnalyzer.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/analyzer/detector/facedetectorimpl/HaarCascadeFaceDetector.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/fragment/CameraFragment.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/fragment/ExplanationPagerAdapter.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/fragment/HomeFragment.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/fragment/JokesFragment.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/fragment/NoSmileFragment.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/fragment/Questionnaire01Fragment.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/fragment/Questionnaire02Fragment.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/fragment/Questionnaire03Fragment.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/fragment/Questionnaire04Fragment.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/fragment/Questionnaire05Fragment.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/fragment/Questionnaire06Fragment.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/fragment/ResultsFragment.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/fragment/SettingsFragment.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/notification/NotificationHandler.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/sync/RemoteSite.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/sync/RemoteSync.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/viewmodel/MeasurementViewModel.kt
Labels: refactor

#67 Minor fixes
  app/src/androidTest/java/de/hsaugsburg/teamulster/sohappy/config/ConfigManagerTest.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/LoadConfigActivity.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/MainActivity.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/config/ConfigManager.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/exceptions/ExceptionHandler.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/fragment/ResultsFragment.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/viewmodel/SettingsViewModel.kt
  app/src/main/res/layout/fragment_results.xml
Labels: bug, refactor

#68 Update README.md
  README.md
Labels: documentation

#70 More fixes
  README.md
  app/build.gradle
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/MainActivity.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/analyzer/ImageAnalyzer.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/config/ConfigManager.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/config/ConfigUtils.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/database/LocalDatabaseManager.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/fragment/CameraFragment.kt
  app/src/main/java/de/hsaugsburg/teamulster/sohappy/fragment/ResultsFragment.kt
Labels: bug, implement, refactor
